require("dotenv").config()
const express=require("express")
const cors=require ("cors")
const bodyparser=require("body-parser")

const adRoutes=require("./routes/admin.routes")
const catRoutes=require("./routes/category.routes")
const stateRoutes=require("./routes/state.routes")
const cityRoutes=require("./routes/city.routes")
const hpRoutes=require("./routes/hospital.routes")
const spRoutes=require("./routes/specialization.routes")
const hproRoutes=require("./routes/hospro.routes")
const docRoutes=require("./routes/doctor.routes")
const testRoutes=require("./routes/test.routes")
const disRoutes=require("./routes/diseases.routes")
const docproRoutes=require("./routes/docpro.routes")
const causeRoutes=require("./routes/cause.routes")
const factorRoutes=require("./routes/factor.routes")
const subfactorRoutes=require("./routes/subfactor.routes")
const SymRoutes=require("./routes/symptom.router")
const organRoutes=require("./routes/organ.routes")
const healthriskRoutes=require("./routes/healthrisk.routes")
const ngoRoutes=require("./routes/ngo.routes")
const govRoutes=require("./routes/govhospitals.routes")
const schemesRoutes=require("./routes/schemes.routes")
const userRoutes=require("./routes/user.routes")
const packageRouter=require("./routes/package.routes")
const adminbookRouter=require("./routes/bookofpackage.routes")


const app=express()
app.use(cors())
app.use(bodyparser.json())

app.use('/api/admin',adRoutes)
app.use('/api/category',catRoutes)
app.use('/api/state',stateRoutes)
app.use('/api/city',cityRoutes)
app.use('/api/hospital',hpRoutes)
app.use('/api/specialization',spRoutes)
app.use('/api/hospro',hproRoutes)
app.use('/api/doctor',docRoutes)
app.use('/api/test',testRoutes)
app.use('/api/diseases',disRoutes)
app.use('/api/docpro',docproRoutes)
app.use('/api/cause',causeRoutes)
app.use('/api/symptom',SymRoutes)
app.use('/api/factor',factorRoutes)
app.use('/api/subfactor',subfactorRoutes)
app.use('/api/organ',organRoutes)
app.use('/api/ngo',ngoRoutes)
app.use('/api/govhospital',govRoutes)
app.use('/api/schemes',schemesRoutes)
app.use('/api/healthrisk',healthriskRoutes)
app.use("/api/user",userRoutes)
app.use("/api/packages",packageRouter)
app.use("/api/bookofpackage",adminbookRouter)
app.use('/hospital_image',express.static('hospital_image'))
app.use('/doctor_image',express.static('doctor_image'))
app.use('/healthrisk_image',express.static('healthrisk_image'))



PORT=process.env.PORT||5000;
app.listen(PORT,()=>console.log(`server is running on ${PORT}`));
require("dotenv").config()
